from manim import *
class detox(Scene):
    def construct(self):
        title=Text("Mastering your craft is a highly effective way ",color=PURE_GREEN).scale(0.65)
        basel=Text("to neutralize toxic relationships.",color=LOGO_RED).scale(0.5)
        title.next_to(basel,UP,buff=1)
        self.play(Write(title),run_time=5)      
        self.play(Write(basel),run_time=5)  
        ul1=Underline(title,color=PURE_RED)
        self.play(GrowFromCenter(ul1))   
        ul12=Underline(basel,color=PURE_BLUE)
        self.play(GrowFromCenter(ul12))      
        self.play(Flash(title[0]),color=GREEN,line_length=15,num_lines=15)  
        self.wait(1)     
        self.play(FadeOut(title),FadeOut(basel),FadeOut(ul1),FadeOut(ul12))
        
        title1=Text("By dedicating your energy to personal and professional growth,  ",color=PURE_GREEN).scale(0.65)
        basel1=Text(", build unshakeable self-confidence, ",color=LOGO_RED).scale(0.5)
        basel2=Text(", you naturally shift your focus away from negativity, ",color=LOGO_RED).scale(0.5)
        basel3=Text(", and attract a healthier network of peers who value your drive.",color=LOGO_RED).scale(0.5)    
        title1.next_to(basel1,UP,buff=2)
        basel2.next_to(basel1,UP,buff=1)
        basel3.next_to(basel1,DOWN,buff=1)
        self.play(Write(title1),run_time=5)      
        self.play(Write(basel2),run_time=5)
        self.play(Write(basel1),run_time=5)     
        self.play(Write(basel3),run_time=5)     
        self.wait(2)               
        self.play(FadeOut(title1),FadeOut(basel2),FadeOut(basel1),FadeOut(basel3),)
        
        title11=Text("1.	The Power of Hyper-Focus | Drowns out the noise: ",color=PURE_GREEN).scale(0.65)

        basel11=Text("leaving less mental bandwidth to ruminate on toxic drama. | Raises your standards: ",color=LOGO_RED).scale(0.5)
        basel12=Text("When you are deeply invested in deliberate practice, your mind is occupied with growth",color=LOGO_RED).scale(0.5)
        basel13=Text("As you become highly competent in your field, you quickly realize your time and ",color=LOGO_RED).scale(0.5)    
        basel14=Text("energy are valuable，making it much easier to walk away from people who drain you.",color=LOGO_RED).scale(0.5)         
        title11.next_to(basel11,UP,buff=2)
        basel12.next_to(basel11,UP,buff=1)
        basel13.next_to(basel11,DOWN,buff=1)
        basel14.next_to(basel11,DOWN,buff=2)        
        self.play(Write(title11),run_time=5)      
        self.play(Write(basel12),run_time=5)
        self.play(Write(basel11),run_time=5)     
        self.play(Write(basel13),run_time=5)   
        self.play(Write(basel14),run_time=5)    
        self.wait(2)                      
        self.play(FadeOut(title11),FadeOut(basel12),FadeOut(basel11),FadeOut(basel13),FadeOut(basel14))
        
    
        title21=Text("2.	Shifting Your Environment : ",color=PURE_GREEN).scale(0.65)
        basel21=Text(",accomplished ones.Honing your skills places you in new circles.",color=LOGO_RED).scale(0.5)
        basel22=Text("The quickest way to outgrow a toxic crowd is to surround oneself with driven",color=LOGO_RED).scale(0.5)                
        basel23=Text("Attraction, not just rejection: Instead of fighting negativity,you magnetize",color=LOGO_RED).scale(0.5)    
        basel24=Text("opportunities and individuals that align with your new level of expertise.",color=LOGO_RED).scale(0.5)         
        title21.next_to(basel21,UP,buff=2)
        basel22.next_to(basel21,UP,buff=1)
        basel23.next_to(basel21,DOWN,buff=1)
        basel24.next_to(basel21,DOWN,buff=2)        
        self.play(Write(title21),run_time=5)      
        self.play(Write(basel22),run_time=5)
        self.play(Write(basel21),run_time=5)     
        self.play(Write(basel23),run_time=5)   
        self.play(Write(basel24),run_time=5)   
        self.wait(2)                       
        self.play(FadeOut(title21),FadeOut(basel22),FadeOut(basel21),FadeOut(basel23),FadeOut(basel24))
        
        title21=Text("3.Building Bulletproof Self-Worth:",color=PURE_GREEN).scale(0.65)
        basel21=Text("the subjective.(and often manipulative) opinions of toxic individuals.",color=LOGO_RED).scale(0.5)
        basel22=Text("The more skilled you become, the more you rely on objective achievements rather than ",color=LOGO_RED).scale(0.5)
        basel23=Text("Specialized skills often lead to better opportunities, providing the tangible freedom",color=LOGO_RED).scale(0.5)    
        basel24=Text(" required to physically remove yourself from toxic living or working situations.",color=LOGO_RED).scale(0.5)         
        title21.next_to(basel21,UP,buff=2)
        basel22.next_to(basel21,UP,buff=1)
        basel23.next_to(basel21,DOWN,buff=1)
        basel24.next_to(basel21,DOWN,buff=2)        
        self.play(Write(title21),run_time=5)      
        self.play(Write(basel22),run_time=5)
        self.play(Write(basel21),run_time=5)     
        self.play(Write(basel23),run_time=5)   
        self.play(Write(basel24),run_time=5)    
        self.wait(2)     
        self.play(Circumscribe(basel23),Circumscribe(basel23),stroke_width = 15)
        self.play(Indicate(basel24,color=GREEN,scale_factor=0.5),Indicate(basel23,color=GREEN,scale_factor=1.3))             
        self.play(FadeOut(title21),FadeOut(basel22),FadeOut(basel21),FadeOut(basel23),FadeOut(basel24))